version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:14.2
    environment:
      POSTGRES_USER: "mkebbehs"
      POSTGRES_PASSWORD: "Zaynxbela1"
      POSTGRES_DB: "mks_userDB"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mkebbehs -d mks_userDB"]
      interval: 10s
      timeout: 5s
      retries: 5

  go:
    container_name: go
    build:
      context: .
    environment:
      PORT: "3080"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_USER: "mkebbehs"
      DB_PASS: "Zaynxbela1"
      DB_NAME: "mks_userDB"
    volumes:
    - ./:/go/src/mks-login-api-docker   
    depends_on:
      postgres:
        condition: service_healthy # waiting until heathcheck of postgres is good
    ports:
      - "3080:3080"

volumes:
  dbdata: # persist database